# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_historical_sports_sport_odds_get200_response_data_inner_bookmakers_inner_markets_inner import V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner

class TestV4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner(unittest.TestCase):
    """V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner:
        """Test V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner`
        """
        model = V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner()
        if include_optional:
            return V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner(
                key = 'h2h',
                last_update = '2023-10-10T12:10:29Z',
                outcomes = [{"name":"Houston Texans","price":2.23},{"name":"Kansas City Chiefs","price":1.45}]
            )
        else:
            return V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner(
        )
        """

    def testV4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner(self):
        """Test V4HistoricalSportsSportOddsGet200ResponseDataInnerBookmakersInnerMarketsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
