# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_sports_sport_events_get200_response_inner import V4SportsSportEventsGet200ResponseInner

class TestV4SportsSportEventsGet200ResponseInner(unittest.TestCase):
    """V4SportsSportEventsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4SportsSportEventsGet200ResponseInner:
        """Test V4SportsSportEventsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4SportsSportEventsGet200ResponseInner`
        """
        model = V4SportsSportEventsGet200ResponseInner()
        if include_optional:
            return V4SportsSportEventsGet200ResponseInner(
                id = 'e912304de2b2ce35b473ce2ecd3d1502',
                sport_key = 'americanfootball_nfl',
                sport_title = 'NFL',
                commence_time = '2023-10-11T23:10Z',
                home_team = 'Houston Texans',
                away_team = 'Kansas City Chiefs'
            )
        else:
            return V4SportsSportEventsGet200ResponseInner(
        )
        """

    def testV4SportsSportEventsGet200ResponseInner(self):
        """Test V4SportsSportEventsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
