# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.outcome import Outcome

class TestOutcome(unittest.TestCase):
    """Outcome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Outcome:
        """Test Outcome
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Outcome`
        """
        model = Outcome()
        if include_optional:
            return Outcome(
                name = 'Houston Texans',
                price = 2.23,
                point = 20.5,
                description = '',
                link = '',
                sid = '',
                bet_limit = 1.337
            )
        else:
            return Outcome(
        )
        """

    def testOutcome(self):
        """Test Outcome"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
