# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_sports_sport_scores_get200_response_inner import V4SportsSportScoresGet200ResponseInner

class TestV4SportsSportScoresGet200ResponseInner(unittest.TestCase):
    """V4SportsSportScoresGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4SportsSportScoresGet200ResponseInner:
        """Test V4SportsSportScoresGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4SportsSportScoresGet200ResponseInner`
        """
        model = V4SportsSportScoresGet200ResponseInner()
        if include_optional:
            return V4SportsSportScoresGet200ResponseInner(
                id = 'e912304de2b2ce35b473ce2ecd3d1502',
                sport_key = 'americanfootball_nfl',
                sport_title = 'NFL',
                commence_time = '2023-10-11T23:10Z',
                completed = True,
                home_team = 'Houston Texans',
                away_team = 'Kansas City Chiefs',
                scores = [{"name":"Houston Texans","score":"20"},{"name":"Kansas City Chiefs","score":"34"}],
                last_update = '2023-10-11T23:30:12Z'
            )
        else:
            return V4SportsSportScoresGet200ResponseInner(
        )
        """

    def testV4SportsSportScoresGet200ResponseInner(self):
        """Test V4SportsSportScoresGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
