# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_historical_sports_sport_events_get200_response import V4HistoricalSportsSportEventsGet200Response

class TestV4HistoricalSportsSportEventsGet200Response(unittest.TestCase):
    """V4HistoricalSportsSportEventsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4HistoricalSportsSportEventsGet200Response:
        """Test V4HistoricalSportsSportEventsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4HistoricalSportsSportEventsGet200Response`
        """
        model = V4HistoricalSportsSportEventsGet200Response()
        if include_optional:
            return V4HistoricalSportsSportEventsGet200Response(
                timestamp = '2023-10-10T12:10:39Z',
                previous_timestamp = '2023-10-10T12:05:39Z',
                next_timestamp = '2023-10-10T12:15:39Z',
                data = [
                    openapi_client.models._v4_sports__sport__events_get_200_response_inner._v4_sports__sport__events_get_200_response_inner(
                        id = 'e912304de2b2ce35b473ce2ecd3d1502', 
                        sport_key = 'americanfootball_nfl', 
                        sport_title = 'NFL', 
                        commence_time = '2023-10-11T23:10Z', 
                        home_team = 'Houston Texans', 
                        away_team = 'Kansas City Chiefs', )
                    ]
            )
        else:
            return V4HistoricalSportsSportEventsGet200Response(
        )
        """

    def testV4HistoricalSportsSportEventsGet200Response(self):
        """Test V4HistoricalSportsSportEventsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
