# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.current_events_api import CurrentEventsApi


class TestCurrentEventsApi(unittest.TestCase):
    """CurrentEventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CurrentEventsApi()

    def tearDown(self) -> None:
        pass

    def test_v4_sports_sport_events_event_id_odds_get(self) -> None:
        """Test case for v4_sports_sport_events_event_id_odds_get

        """
        pass

    def test_v4_sports_sport_events_get(self) -> None:
        """Test case for v4_sports_sport_events_get

        """
        pass

    def test_v4_sports_sport_odds_get(self) -> None:
        """Test case for v4_sports_sport_odds_get

        """
        pass

    def test_v4_sports_sport_scores_get(self) -> None:
        """Test case for v4_sports_sport_scores_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
