# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_historical_sports_sport_events_event_id_odds_get200_response_data_bookmakers_inner import V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner

class TestV4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner(unittest.TestCase):
    """V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner:
        """Test V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner`
        """
        model = V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner()
        if include_optional:
            return V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner(
                key = 'draftkings',
                title = 'DraftKings',
                markets = [
                    openapi_client.models._v4_historical_sports__sport__events__event_id__odds_get_200_response_data_bookmakers_inner_markets_inner._v4_historical_sports__sport__events__eventId__odds_get_200_response_data_bookmakers_inner_markets_inner(
                        key = 'alternate_spreads', 
                        last_update = '2023-10-10T12:10:29Z', 
                        outcomes = [{"name":"Houston Texans","price":5.08,"point":-23.0},{"name":"Houston Texans","price":4.82,"point":-22.5},{"name":"Houston Texans","price":4.66,"point":-22},{"name":"Kansas City Chiefs","price":1.15,"point":23.0},{"name":"Kansas City Chiefs","price":1.17,"point":22.5},{"name":"Kansas City Chiefs","price":1.17,"point":22.0}], )
                    ]
            )
        else:
            return V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner(
        )
        """

    def testV4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner(self):
        """Test V4HistoricalSportsSportEventsEventIdOddsGet200ResponseDataBookmakersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
