# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.score_model import ScoreModel

class TestScoreModel(unittest.TestCase):
    """ScoreModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScoreModel:
        """Test ScoreModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScoreModel`
        """
        model = ScoreModel()
        if include_optional:
            return ScoreModel(
                name = 'Houston Texans',
                score = '20'
            )
        else:
            return ScoreModel(
        )
        """

    def testScoreModel(self):
        """Test ScoreModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
