# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_sports_sport_odds_get200_response_inner import V4SportsSportOddsGet200ResponseInner

class TestV4SportsSportOddsGet200ResponseInner(unittest.TestCase):
    """V4SportsSportOddsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4SportsSportOddsGet200ResponseInner:
        """Test V4SportsSportOddsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4SportsSportOddsGet200ResponseInner`
        """
        model = V4SportsSportOddsGet200ResponseInner()
        if include_optional:
            return V4SportsSportOddsGet200ResponseInner(
                id = 'e912304de2b2ce35b473ce2ecd3d1502',
                sport_key = 'americanfootball_nfl',
                sport_title = 'NFL',
                commence_time = '2023-10-11T23:10Z',
                home_team = 'Houston Texans',
                away_team = 'Kansas City Chiefs',
                bookmakers = [
                    openapi_client.models._v4_sports__sport__odds_get_200_response_inner_bookmakers_inner._v4_sports__sport__odds_get_200_response_inner_bookmakers_inner(
                        key = 'draftkings', 
                        title = 'DraftKings', 
                        last_update = '2023-10-10T12:10:29Z', 
                        markets = [
                            openapi_client.models._v4_sports__sport__odds_get_200_response_inner_bookmakers_inner_markets_inner._v4_sports__sport__odds_get_200_response_inner_bookmakers_inner_markets_inner(
                                key = 'h2h', 
                                last_update = '2023-10-10T12:10:29Z', 
                                outcomes = [{"name":"Houston Texans","price":2.23},{"name":"Kansas City Chiefs","price":1.45}], 
                                link = '', 
                                sid = '', )
                            ], 
                        link = 'https://sportsbook.draftkings.com/event/chi-bears-%40-ind-colts/30568753', 
                        sid = '30568753', )
                    ]
            )
        else:
            return V4SportsSportOddsGet200ResponseInner(
        )
        """

    def testV4SportsSportOddsGet200ResponseInner(self):
        """Test V4SportsSportOddsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
