# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.sports_api import SportsApi


class TestSportsApi(unittest.TestCase):
    """SportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SportsApi()

    def tearDown(self) -> None:
        pass

    def test_v4_sports_get(self) -> None:
        """Test case for v4_sports_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
