# coding: utf-8

"""
    The Odds API

    To access the API, get a free API key from https://the-odds-api.com

    The version of the OpenAPI document: 4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_sports_get200_response_inner import V4SportsGet200ResponseInner

class TestV4SportsGet200ResponseInner(unittest.TestCase):
    """V4SportsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4SportsGet200ResponseInner:
        """Test V4SportsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4SportsGet200ResponseInner`
        """
        model = V4SportsGet200ResponseInner()
        if include_optional:
            return V4SportsGet200ResponseInner(
                key = 'americanfootball_nfl',
                active = True,
                group = 'American Football',
                description = 'US Football',
                title = 'NFL',
                has_outrights = False
            )
        else:
            return V4SportsGet200ResponseInner(
        )
        """

    def testV4SportsGet200ResponseInner(self):
        """Test V4SportsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
